# Generated by Django 2.1.7 on 2019-03-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190304_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(blank=True, to='webapp.Category'),
        ),
    ]
