# Generated by Django 2.1.7 on 2019-03-07 11:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190304_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=webapp.models.generate_code, editable=False, max_length=10, unique_for_date='created_at')),
                ('status', models.CharField(choices=[('created', 'Created'), ('sold', 'Sold'), ('canceled', 'Canceled')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund', models.BooleanField(default=False)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='webapp.Discount', verbose_name='discount')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='webapp.Category'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Hall'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='show',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='webapp.Seat', verbose_name='seat'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='webapp.Show', verbose_name='show'),
        ),
        migrations.AddField(
            model_name='book',
            name='seats',
            field=models.ManyToManyField(related_name='booking', to='webapp.Seat'),
        ),
        migrations.AddField(
            model_name='book',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='webapp.Show'),
        ),
    ]
