# Generated by Django 2.1.7 on 2019-03-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_movie_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='refund',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
