# Generated by Django 2.1.7 on 2019-03-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190307_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='webapp.Discount', verbose_name='discount'),
        ),
    ]
